#! /bin/bash

###############################################################
# Info:
# & send a process to background. Example: discord &
# ! disown a process. Example: discord ! 
# </dev/null &>/dev/null completely silence a process.
# Combinations are possible. Example: discord &!
# alias="" Is created during shell startup and won't change
# alias='' Is created during runtime and will evaluate every time it's called
# $RANDOM will generate a random number from 0 through 32767
# array=('Element1' 'Element2')
###############################################################

scripts=$HOME/.local/scripts
# Fix discord long calls
# alias discord="discord --no-sandbox </dev/null &>/dev/null &"
alias discord="discord --no-sandbox &"
# Recompile ycm (if autocompletion stops working execute this)
alias ycminstall="python3 ~/.vim/plugged/YouCompleteMe/install.py"
# Rclone (be careful!)
alias rclonepull="rclone -P sync drive:Thunderbird ~/.thunderbird ;
rclone -P sync drive:Calibre/Calibre\ Library ~/Calibre\ Library"
alias rclonepush="rclone -P sync ~/.thunderbird drive:Thunderbird ;
rclone -P sync ~/Calibre\ Library drive:Calibre/Calibre\ Library"

# Config Files
alias arch="nvim $scripts/bootstrap/arch_functions"
alias aliases="nvim $ZDOTDIR/aliases"
alias zshenv="nvim ~/.zshenv"
alias zshrc="nvim $ZDOTDIR/.zshrc"
alias zprofile="nvim $ZDOTDIR/.zprofile"
alias xprofile="nvim $HOME/.xprofile"
alias xinitrc="nvim $HOME/.xinitrc"
alias vimrc="nvim ~/.vim/vimrc"
alias bashrc="nvim ~/.bashrc"
alias tmux.conf="nvim ~/.config/tmux/tmux.conf"
#alias vlightdm="sudo vim /etc/lightdm/lightdm.conf"
#alias vpacman="sudo vim /etc/pacman.conf"
#alias vgrub="sudo vim /etc/default/grub"
#alias vmkinitcpio="sudo vim /etc/mkinitcpio.conf"
#alias vslim="sudo vim /etc/slim.conf"
#alias voblogout="sudo vim /etc/oblogout.conf"
#alias vmirrorlist="sudo vim /etc/pacman.d/mirrorlist"
#alias vconfgrub="sudo vim /boot/grub/grub.cfg"

alias n="nvim"

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

## Colorize the grep command output for ease of use (good for log files)##
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# adding flags
alias cp="cp -iv"          # confirm before overwriting something
alias mv="mv -iv"
alias mkd="mkdir -pv"
alias df="df -h"          # human-readable sizes
alias free="free -m"      # show sizes in MB

# Clear
alias c="clear"

# Git
alias gs="git status"
alias gf="git fetch"
alias ga="git add "
alias gm="git merge"
alias gc="git commit -m "
alias gp="git push"
alias gitsync="git submodule sync; git submodule update --init --recursive"
alias gsu="git submodule update --recursive --remote"
## Fun commit
#alias yolo='git add -A; git commit -m "$(curl -s http://whatthecommit.com/index.txt)"; git push'
## Alternative (makes it easier to find out which commits have no message)
alias yolo='git add -A; git commit -m "This is a placeholder"; git push'

# List files
# using -a -a will show '.' and ".."
# --git causes to crash when symbolic link is gone
alias ls="exa -F --long --header --links --group --group-directories-first"
alias la="exa -a -F --long --header --links --group --group-directories-first"
alias lsd="exa -D -a"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# Cpp
#alias eda++="g++ -std=c++11"
alias p1++="g++ -ansi -O2 -DNDEBUG -D_GLIBCXX_DEBUG -Wall -Wextra -Werror -Wno-uninitialized -Wno-sign-compare -Wshadow"
alias p2++="g++ -D GLIBCXX_DEBUG -O2 -Wall -Wextra -Werror -Wno-sign-compare -std=c++11"

# Userlist
alias userlist="cut -d: -f1 /etc/passwd"

# Switch between bash and zsh
alias tobash="sudo chsh $USER -s /bin/bash && echo 'Now log out.'"
alias tozsh="sudo chsh $USER -s /bin/zsh && echo 'Now log out.'"

### MacOS
if [[ "$OSTYPE" == "darwin"* ]]; then
    alias rm="rm -vi"
    alias update="sudo softwareupdate -i -a; 
    brew update; 
    brew upgrade ; 
    brew update --cask"
    alias updateall="sudo softwareupdate -i -a; 
    brew update; 
    brew upgrade; 
    brew update --cask; 
    python3 -m pip install --user --upgrade pynvim;
    vim +PlugUpgrade +PlugUpdate +qall; 
    antigen update; 
    npm install npm -g; 
    xcode-select --install; 
    pip install --upgrade pip"
    # xcode-select --install installs developer tools that need to be updated with every update to MacOS
    alias cleanup="brew cleanup; 
    vim +PlugClean +qall"
    # Recursively delete `.DS_Store` files
    alias clean="find . -type f -name '*.DS_Store' -ls -delete"
fi

if [[ "$OSTYPE" == "linux"* ]]; then

    alias rm="rm -vI"
    # Lock screen
    LockScreens=('pipes.sh' 'cmatrix')
    alias lock='${LockScreens[$RANDOM % 2]}'
    # Get the error messages from journalctl
    alias jctl="journalctl -p 3 -xb"
    # Check vulnerabilities microcode
    alias microcode="grep . /sys/devices/system/cpu/vulnerabilities/*"

    ### Arch & Manjaro
    if [[ "$DISTRO" == "arch" || "$DISTRO" == "manjaro" ]]; then
        alias update="sudo pacman -Syu"
        alias updateall="yay -Syu; 
        python3 -m pip install --user --upgrade pynvim; 
        vim +PlugUpgrade +PlugUpdate +qall; 
        antigen update;"
        # This breaks pacman sudo npm install -g npm; sudo gem update;
        # Cleans pacman and AUR cache and vim no longer used plugins
        alias cleanup="yay -Sc; 
        vim +PlugClean +qall
        sudo pacman -R $(pacman -Qdtq)"
        #pacman unlock
        alias unlock="sudo rm /var/lib/pacman/db.lck"
    fi

    ### Arch
    if [[ "$DISTRO" == "arch" ]]; then
        # Get fastest mirrors in your neighborhood
        alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
    fi

    ### Manjaro
    if [[ "$DISTRO" == "manjaro" ]]; then
        # Update mirrors and update
        alias mirror="sudo pacman-mirrors -f && sudo pacman -Syyu"
    fi

    ### Ubuntu
    if [[ "$DISTRO" == "ubuntu" ]]; then
        alias update="sudo apt-get update; 
        sudo apt-get full-upgrade; 
        brew update; 
        brew upgrade; 
        vim +PlugUpgrade +PlugUpdate +qall; 
        antigen update"
        alias cleanup="sudo apt-get autoclean; 
        sudo apt-get clean; 
        sudo apt-get autoremove; 
        brew cleanup; 
        vim +PlugClean +qall"
        alias tmux="tmux -f ~/.config/tmux/tmux.conf"
    fi
fi

###############################################################
# => Clean home directory
###############################################################

alias Xres="xrdb -load ~/.config/X11/xresources"
#alias nvidia-settings="nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings"
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
