#! /usr/bin/env bash
# Author: https://github.com/cuberhaus

#https://raymondjdouglas.com/blog/2019/airpods-on-arch/
#Chrome disable this:
#chrome://flags/#global-media-controls-modern-ui
### VARIABLES
scripts=$HOME/.local/scripts
flags="-S --noconfirm --needed"
pac="sudo pacman $flags"
yay="yay $flags"
myTerminal="kitty"

### FUNCTIONS
## Invariant: be at $HOME dir
emacs() {
    pip3 install ptvsd                          # for python dap
    $pac languagetool                           # languagetool for emacs
    $pac mplayer                                # for pomodoro sound
}
base_install () {
    $pac conky
    $pac adapta-gtk-theme                       # Alternative theme
    $pac arc-gtk-theme                          # Arc theme and its icon's
    $pac arc-icon-theme                         # Doesn't install in manjaro
    $pac base-devel                             # AUR
    $pac bat                                    # "Cat" on steroids
    $pac biber                                  # Latex bibliography
    $pac breeze                                 # theme
    $pac calibre                                # Book manager
    $pac cron                                   # Backups (sudo timeshift-gtk)
    $pac dconf-editor                           # Edit gnome configuration
    $pac dex
    $pac discord
    $pac dnsutils                               # Ip
    $pac dunst                                  # Notifications
    $pac dunstify                               # dunst notification
    $pac exa                                    # "ls" on steroids
    $pac exfat-utils                            # Add support for exfat https://wiki.archlinux.org/index.php/file_systems
    $pac file-roller                            # Archive Manager (extract, unzip...)
    $pac firefox                                # chrome doesn't redirect to wifi page's
    $pac fzf                                    # Fuzzy finder
    $pac gcc                                    # Cpp
    $pac gdb                                    # debugging c++
    $pac git                                    # It's git bro
    $pac gnome-calculator                       # Calculator
    $pac gnome-font-viewer                      # Font viewer
    $pac gnome-keyring                          # https://wiki.archlinux.org/title/GNOME/Keyring
    $pac gtk2 gtk3
    $pac gucharmap                              # Characters keyboard
    $pac gvim                                   # Vim version with extra features
    $pac hardinfo cpu-x                         # pc information
    $pac htop                                   # Show system resources
    $pac inotify-tools                          # inotifywatch -r $file (to watch if those files have been accessed)
    $pac kcolorchooser                          # Color picker
    $pac kdiff3                                 # git best mergetool (complex merges are better than meld)
    $pac kitty                                  # Terminal emulator
    $pac kvantum-qt5                            # Qt5 Custom themes
    $pac laptop-detect                          # Detect if using a laptop
    $pac libmythes mythes-en mythes-es  # Libre office Synonyms
    $pac libreoffice-still libreoffice-still-ca # (install plugins located on .local)
    $pac lxappearance                           # Gtk configuration utility
    # $pac meld                                   # Best diff viewer
    $pac ncdu                                   # Manage storage
    $pac nemo
    $pac nemo-fileroller
    $pac nemo-preview
    $pac nemo-seahorse
    $pac nemo-share
    $pac net-tools                              # Ips
    $pac nilfs-utils                            # Manage partitions
    $pac nomacs                                 # Image viewer (da best)
    $pac noto-fonts-emoji                       # Classic Emoji
    $pac npm                                    # Package manager
    $pac ntfs-3g                                # Read/write support for ntfs https://wiki.archlinux.org/index.php/NTFS-3G
    $pac okular                                 # Best pdf viewer
    $pac papirus-icon-theme                     # Best icon theme!
    $pac partitionmanager                       # Partition manager for KDE
    $pac perl-file-mimeinfo                     # mimeopen -d $file and type whatever app you want to open that with
    $pac playerctl                              # Audio
    $pac polkit                                 # Policy kit
    $pac polkit-gnome                           # https://wiki.archlinux.org/index.php/Polkit
    $pac python
    $pac python3
    $pac qt5ct                                  # Qt5 configuration utility
    $pac ranger                                 # Ranger
    $pac rclone                                 # Rsync to remote
    $pac reflector                              # Update Arch mirrors
    $pac remmina freerdp libvncserver           # Remote conexions
    $pac ruby                                   # Package manager
    $pac seahorse                               # Password keeper
    $pac speedcrunch                            # Fast calculations
    $pac stow                                   # To deploy dotfiles
    $pac svn                                    # Similar to git
    $pac the_silver_searcher                    # Better and faster ack (and grep)
    $pac thunderbird                            # $yay  thunderbird-bin
    $pac tmux                                   # Terminal multiplexer
    $pac transmission-gtk                       # A simpler Torrent D.
    $pac trash-cli                              # https://wiki.archlinux.org/index.php/Trash_management
    $pac ttf-dejavu ttf-liberation ttf-droid ttf-ubuntu-font-family ttf-roboto noto-fonts        # Fonts
    $pac tumbler ffmpegthumbnailer raw-thumbnailer        # IDK
    $pac udftools                               # Manage partitions
    $pac udiskie                                # Automater
    $pac udisks2                                # Daemon to manipulate storage devices
    $pac vlc                                    # Video player
    $pac w3m                                    # Preview images on ranger
    $pac wget                                   # Download stuff
    $pac wireshark                              # View incoming/outgoing connections
    $pac wmctrl                                 #used for scripting
    $pac xclip                                  # Clipboard
    $pac xdg-user-dirs                          # Manage user directories like "Downloads" https://wiki.archlinux.org/index.php/XDG_user_directories
    $pac xfce4-clipman-plugin                   # Clipboard manager (persistant clip even when application is closed)
    $pac xorg                                   # Display server
    $pac xorg-xinit                             # Start X11 without LightDM "startx"  https://wiki.archlinux.org/index.php/Xinit
    $pac xss-lock                               # Lockscreen
    $pac yarn                                   # Package installer
    $pac zsh                                    # Zsh shell
    $pac zathura-cb # zathura needs plugins
    $pac zathura-djvu
    $pac zathura-pdf-mupdf
    $pac zathura-ps
    $pac zathura

    # DO NOT CHANGE THIS ORDER YAY COMES AFTER pac
    yay_install

    $yay balena-etcher                          # "Rufus" on linux
    $yay betterlockscreen                       # Lockscreen
    $yay f5fpc                                  # Connexio a UPClink
    $yay google-chrome                          # Best web browser
    $yay libreoffice-extension-languagetool     # Libre office Grammar
    # $yay spotify                                # Spotify
    sudo snap spotify                           # Spotify only on manjaro
    $yay timeshift                              # Backups (sudo timeshift-gtk)
    $yay tomighty                               # Pomodoro timer (take a break from life, read a book, contemplate life, make coffee...)
    $yay ttf-ms-fonts                           # Microsoft fonts ##deprecated
    $yay visual-studio-code-bin                 # Microsoft's Visual Code /not #$pac  code
    $yay whatsapp-nativefier                    # Whatsapp client
    $yay obsidian                               # Markdown editor

    #https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications
    #https://wiki.archlinux.org/index.php/qt

    # This has to go after installing nemo
    # Nemo "best filemanager"
    gsettings set org.cinnamon.desktop.default-applications.terminal exec $myTerminal # Tell Nemo to use Termite instead of gnome-terminal
    # gsettings set org.cinnamon.desktop.default-applications.terminal exec-arg  -e # Termite execute argument is -e in gnome-terminal its -x
}

arch_install() {
    # Drivers
    $pac linux
    $pac linux-headers
    # LTS release
    #$pac linux-lts
    #$pac linux-lts-headers
    #$pac nvidia-lts
    # $pac nvidia-dkms #very slow
    $pac nvidia nvidia-utils                    # Nvidia
    $pac xf86-video-intel mesa lib32-mesa       # Intel
    $pac lib32-nvidia-utils                     # Requires adding multilib libraries
    $pac nvidia-settings                        # Add force composition pipeline in nvidia-settings

    # Printers
    # https://wiki.archlinux.org/index.php/CUPS
    # https://wiki.archlinux.org/title/CUPS#Web_interface
    # https://wiki.archlinux.org/title/Avahi#Hostname_resolution
    $pac cups system-config-printer # printers
    if [[ $FirstRun == y || $FirstRun == Y ]]; then
        sudo systemctl enable org.cups.cupsd.service
        sudo systemctl start org.cups.cupsd.service
    fi

    # Bluetooth
    $pac  bluez bluez-utils $pac  blueberry     # Linux Mint GNOME Bluetooth
    if [[ $FirstRun == y || $FirstRun == Y ]]; then
        systemctl enable bluetooth.service
    fi
    $yay pulseaudio-modules-bt  # High quality audio codecs

    # Display manager
    if [[ $FirstRun == y || $FirstRun == Y ]]; then
        systemctl enable lightdm.service
    fi
    $pac lightdm-gtk-greeter lightdm lightdm-gtk-greeter-settings

    # Ntp for time syncro
    #https://wiki.archlinux.org/index.php/Systemd-timesyncd
    if [[ $FirstRun == y || $FirstRun == Y ]]; then
        systemctl enable systemd-timesyncd.service   # systemd time service
        sudo timedatectl set-ntp true                # Enable ntp
        systemctl disable ntpd.service
    fi
    # https://wiki.archlinux.org/index.php/USB_storage_devices

    # Network Manager and enable daemon on startup
    $pac networkmanager
    $pac nm-connection-editor # Gui
    $pac nm-applet # Applet
    if [[ $FirstRun == y || $FirstRun == Y ]]; then
        systemctl enable NetworkManager.service
    fi
}

arch_and_manjaro() {
    $pac hplip # hp printer
    $yay epson-inkjet-printer-escpr # epson printer
    # samba
    sudo mkdir /var/lib/samba/usershares
    sudo groupadd -r sambashare
    sudo chown root:sambashare /var/lib/samba/usershares
    sudo chmod 1770 /var/lib/samba/usershares
    sudo gpasswd sambashare -a your_username

    # /etc/samba/smb.conf
    # [global]
    # usershare path = /var/lib/samba/usershares
    # usershare max shares = 100
    # usershare allow guests = yes
    # usershare owner only = yes
}

manjaro() {
    $pac manjaro-pipewire
    # Make airpods work
    sudo sed -i "s/#ControllerMode = dual/ControllerMode = bredr/" /etc/bluetooth/main.conf
}

yay_install() {
    cd $HOME/
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si
    sudo rm -r $HOME/yay
}

vim_install () {
    $pac  neovim
    cd $HOME
    vim +PlugInstall +qall
    # Vim YouCompleteMe plugin install
    bash $scripts/ycm.sh
    $pac python2 python-pip
    pip install wheel
    sudo npm install -g neovim
    python3 -m pip install --user --upgrade pynvim
    sudo gem install neovim
}

# Best Tiling Window Manager
i3_install () {
    # AUR
    $yay cava                                   # https://github.com/karlstav/cava
    $yay kbdd-git                               # i3blocks keyboard layout

    # GUI/Terminal
    # $pac pipewire-pulse                         # New and improved sound, uses SBC and ACC out of the box (pulseaudio deprecated)
    $pac acpi
    $pac awk bc upower                          # Battery plus
    $pac feh                                    # Wallpaper
    $pac flameshot                              # Screenshots
    $pac i3-gaps                                # i3 with gaps
    $pac i3blocks                               # Bottom bar
    $pac light                                  # Brightness
    $pac perl-anyevent-i3 python-dbus
    $pac picom                                  # Compositor, for transparencies
    # $pac pulseaudio alsa-utils                  # Audio
    # $pac pulseaudio pulseaudio-equalizer         pulseaudio-bluetooth        # Audio
    $pac rofi                                   # App menu Super+d
    $pac yad xdotool                            # Calendar
    $pac zenity                                 # Poweroff menu i3blocks
    #$yay installs this: $pac  jq xdotool indent perl-anyevent-i3        # cava dependancies
}

xmonad_install () {
    $pac trayer                                 # xmonad add a tray for apps
    $pac xmobar                                 # Best bar for xmonad
    $pac xmonad-contrib                         # Xmonad with extra plugins
    $pac xorg-xmessage                          # xmonad send messages
}

# Best Desktop
cinnamon_install() {
    # GUI
    $pac cinnamon                               # Desktop
    $pac gnome-screenshot                       # Take screenshots with impr pant
    $pac gnome-shell                            # Fallback mode in case cinnamon crashes, to have a taskbar
    $pac metacity                               # Fallback mode in case cinnamon crashes
    $pac python-numpy python-xlib               # Color pick applet

    # AUR
    $yay cinnamon-sound-effects                 # Sound effects
    $yay mint-themes mint-y-icons mint-backgrounds        # Themes

    gsettings set org.cinnamon.desktop.wm.preferences resize-with-right-button true # alt + rightclick to resize windows
    # Uninstall  xf86-video-intel
    #https://wiki.archlinux.org/index.php/cinnamon
    # To fix laggy animations
    #https://www.reddit.com/r/linuxmint/comments/7v2jt6/laggy_cinnamon_animations/
    # Edit animation time (0.05)/usr/share/cinnamon/js/ui/expo.js
    # and /usr/share/cinnamon/js/ui/overview.js
}

gnome_install() {
    $pac chrome-gnome-shell
    # Extensions
    # dash to dock (add dock)
    # impatience (faster animations)
    # auto move windows (move apps to workspaces automatically)
    # WinTile (tile quarter windows)
    # cpu power manager (cpu management)
}

plasma_install() {
    $pac  plasma                                # Check archwiki first
    $yay  ocs-url                               # Easy install of kde store add-ons
}

bloat_install () {
    $pac cmatrix                                # Bloat
    $pac cowsay                                 # A cow displaying text
    $pac fortune-mod                            # Random quote
    $pac lolcat
    $pac ponysay asciiquarium
    $pac sl                                     # Steam locomotor, (Did you mean to type ls?)
    $yay figlet toilet                          # Cool letters
    $yay pipes.sh                               # Lockscreens
}

#https://wiki.manjaro.org/index.php/VirtualBox
virtualbox_install() {
    $pac virtualbox # Need to activate virtualization in bios
    $pac virtualbox-host-modules-arch # 'linux' kernel
    $pac virtualbox-host-dkms # other kernels including linux-lts
}

games_install () {
    $pac dnsmasq
    $pac lutris
    $pac minecraft
    $pac steam
    #$pac steam-manjaro
    $pac vulkan-tools
}

### DO ONCE
# This function enables NaturalScrolling for the touchpad
trackpad_scrolling () {
    sudo touch /etc/X11/xorg.conf.d/30-touchpad.conf
    echo 'Section "InputClass"
    Identifier "libinput touchpad catchall"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    Driver "libinput"
    Option "NaturalScrolling" "true"
    EndSection' | sudo tee -a /etc/X11/xorg.conf.d/30-touchpad.conf
}

activate_reisub () {
    echo kernel.sysrq=1 | sudo tee --append /etc/sysctl.d/99-sysctl.conf
    sudo update-grub
}

laptop_install() {
    $pac tlp        # Manage resources to improve battery usage
    sudo systemctl enable tlp.service
    trackpad_scrolling
}

dwall() {
    cd $HOME
    git clone https://github.com/adi1090x/dynamic-wallpaper.git
    cd dynamic-wallpaper
    chmod +x install.sh
    ./install.sh
    cd $HOME
    sudo rm -r $HOME/dynamic-wallpaper
}

doom_emacs_install () {
    $pac emacs
    $pac ripgrep
    $pac fd
    # DOOM
    git clone --depth 1 https://github.com/hlissner/doom-emacs $HOME/.emacs.d
    $HOME/.emacs.d/bin/doom install
}

### All packages in here should be handpicked
optional() {
    # Trash
    # $pac arduino-avr-core arduino #usermod -aG uucp,lock pol
    # $pac conky                          # Desktop rice
    # $pac dhcpcd                         # Internet
    # $pac github-cli                    # Github for terminal, create issues...
    # $pac gnome-disk-utility             # Partition manager by gnome
    # $pac gparted                       # Manage partitions (doesn't work with ex-fat)
    # $pac libreoffice-fresh libreoffice-fresh-ca # Do not ever use this as it can contain breaking bugs that may cause it to crash
    # $pac pix
    # $yay birdtray                               # Thunderbird tray (obsolete with shortcuts)
    # $yay eclipse-java                           # BD

    # Apps
    $pac audacity                               # Audio editor
    $pac gimp                                   # Image editor
    $pac obs-studio                             # Video recording
    $pac texstudio                              # Latex text editor
    $pac tor; $yay tor-browser
    $yay skypeforlinux-stable-bin               # Skype
    $yay slack-desktop                          # Slack
    $yay youtube-dl                             # Download youtube videos
    # $yay conky-cairo-no-nvidia                  # fix lua
    # $yay conky-manager2-git
    # $yay electron9-bin # idk what this does

    # Programming tools
    $yay ddd                          # debugging c++
    $pac doxygen texlive-most graphviz          # Doxygen
    $pac jdk-openjdk
    $pac protege # IA https://protege.stanford.edu/products.php better to download zip
    $pac qtcreator glm qt5-tools qt5-webkit     # OpenGL, QT, C++
    $pac r                                      # Probabilitat i estadística
    $pac ghc                                    # Haskell compiler
    $pac cabal-install                          # Haskell build tools to compile haskell programs
    $pac hlint                                  # Haskell linter
    $pac haskell-language-server                # Haskell It provides IDE-like features such as code completion, “goto definition”, documentation on hover, linting, formatting or refactoring for any editor integrating with the LSP.It provides IDE-like features such as code completion, “goto definition”, documentation on hover, linting, formatting or refactoring for any editor integrating with the LSP.
    $yay android-studio                         # Android Studio
    $yay clion clion-jre                        # C++ IDE
    $yay clips # IA SBC
    $yay intellij-idea-ultimate-edition         # BD paid IntelliJ
    $yay intellij-idea-ultimate-edition-jre     # Best java IDE
    $yay pycharm-professional                   # One of the best python IDE besides vscode
    $yay rstudio-desktop-bin                    # Probabilitat i estadística IDE
    $yay swi-prolog-devel                       # Prolog programming language
    $yay visual-paradigm-community              # IES, PROP

    curl -O https://download.sublimetext.com/sublimehq-pub.gpg && sudo pacman-key --add sublimehq-pub.gpg && sudo pacman-key --lsign-key 8A8F901A && rm sublimehq-pub.gpg

    echo -e "\n[sublime-text]\nServer = https://download.sublimetext.com/arch/stable/x86_64" | sudo tee -a /etc/pacman.conf
    sudo pacman -Syu sublime-text
    sudo pacman -Syu sublime-merge


    #LP compiladors
    $pac lilypond timidity ffmpeg
    pip3 install antlr4-python3-runtime

    # Bases de dades
    $pac pgadmin4
    $pac dbeaver
    # Base de dades https://wiki.archlinux.org/index.php/Java#Switching_between_JVM https://bbs.archlinux.org/viewtopic.php?id=262107 https://wiki.archlinux.org/index.php/PostgreSQL https://wiki.archlinux.org/index.php/Dbeaver (if it doesn't work check used java version)
    #$pac  intellij-idea-community-edition  # BD free version (no SQL)

    #XC read this to install
    # https://wiki.archlinux.org/index.php/PacketTracer
}
