#! /usr/bin/env bash
# Author: https://github.com/cuberhaus
set -euo pipefail

### VARIABLES
scripts="$HOME/.local/scripts"
source "$scripts/bootstrap/base_functions"
source "$scripts/bootstrap/arch_functions"

### FIRST RUN
read -rp "Is this a first-time install? (y/n): " FirstRun
export FirstRun

### INSTALLATION
info "Updating system..."
sudo pacman -Syu

install_preparation

echo "#! /bin/sh
export DISTRO=arch" > "$HOME/.config/distro"  # Distro variable
sudo cp "$HOME/dotfiles/dotfiles/.local/share/icons/Avatar.jpg" /usr/share/icons/Avatar.jpg # Move avatar picture so that LightDM can find it

### ONLY CHANGE FROM HERE ON
base_install
arch_install
i3_install
xmonad_install

#applets                                    # Installs Cinnamon applets (implement pending)
#bloat_install
#cinnamon_install
#games_install
#gnome_install
#optional
#plasma_install
#virtualbox_install
apps_AUR_install
cava_install
dwall
if [[ "${FirstRun}" == y || "${FirstRun}" == Y ]]; then
    laptop_install # DO ONLY ONCE
    activate_reisub # DO ONLY ONCE
fi
ai_tools_install
vim_install
wget -qO- https://git.io/papirus-folders-install | sh # Install folder colors https://github.com/PapirusDevelopmentTeam/papirus-folders
if [ "$(basename "$SHELL")" != "zsh" ]; then
    chsh -s "$(which zsh)"                  # Change default shell to zsh
fi

apply_skip_worktree
info "Bootstrap complete!"
