#! /usr/bin/env bash
### COMMENTS
# YOU NEED TO ADD YOURSELF TO WHEEL AND TO VIDEO
# video makes backlight work and wheel gives you sudo privilege
# usermod -a -G wheel video input
# Configure nvidia nvidia-xconfig
# Wallpaper error when background is set in desktop, it will also be used by
# LightDM unless the picture isn't coming from /usr/share/backgrounds

### VARIABLES
scripts=$HOME/.local/scripts
source $scripts/bootstrap/arch_functions # Include functions

### INSTALLATION
cd ~/
sudo pacman -Syu # Update

# Distro variable
echo "#! /bin/sh
export DISTRO=arch" > ~/.config/distro
yay_install # Needed to install AUR packages

### ONLY CHANGE FROM HERE ON
base_install
arch_install
i3_install

### FUNCTIONS
#applets             # Installs Cinnamon applets # implement pending
#bloat_install
#cinnamon_install
#games_install
#gnome_install
#optional
#plasma_install
#virtualbox_install
apps_AUR_install
cava_install
dwall
laptop_install
vim_install
wget -qO- https://git.io/papirus-folders-install | sh # Install folder colors https://github.com/PapirusDevelopmentTeam/papirus-folders
chsh -s $(which zsh) # Change default shell to zsh
