#!/bash/sh
### VARIABLES
scripts=$HOME/.local/scripts
source $scripts/bootstrap/mac_functions # Include functions

### INSTALLATION
app_store_install
brew_install
mac_install
vim_install
#bloat_install
#doom_emacs_install
