#!/usr/bin/env bash
# Author: https://github.com/cuberhaus
set -euo pipefail

### VARIABLES
scripts="$HOME/.local/scripts"
source "$scripts/bootstrap/base_functions"
source "$scripts/bootstrap/mac_functions"

### INSTALLATION
install_preparation
#app_store_install
brew_install
mac_install
ai_tools_install
vim_install
#bloat_install
#doom_emacs_install

info "Bootstrap complete!"
