#!/bash/sh
# Author: https://github.com/cuberhaus

# Remember to setup rclone and then rclonepull_calibre rclonepull_thunderbird
# https://support.mozilla.org/en-US/kb/profiles-where-thunderbird-stores-user-data
# /Applications/Thunderbird.app/Contents/MacOS/thunderbird-bin -ProfileManager
# ~/Library/Thunderbird/Profiles/xxxxxxxx.default/

#delete .xinitrc shortcut because it conflicts with xquartz and will open and close indefinitely.
brew_install() {
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
}

mac_install () {
    touch $HOME/.hushlogin                      # Avoid terminal prompts
    touch ~/.bash_sessions_disable              # Share history through sessions
    sudo chown -R pol ~/.cache/zsh              # zsh history doesn't work when owner is wrong
    ### Terminal stuff
    brew install pinentry-mac                   # for prompts git password
    brew install smimesign                      # git with gpg
    brew install ack
    brew install astyle
    brew install bat                            # Cat on steroids (for ranger)
    brew install bison
    brew install cmake
    brew install exa                            # "ls" on steroids
    brew install flex
    brew install fzf                            # Fuzzy Finder
    brew install git                            # Git
    brew install go
    brew install gpg
    brew install htop                           # Resource viewer
    brew install llvm                           # Compiler
    brew install mono
    brew install ncdu                           # Storage manager
    brew install neofetch                       # System info
    brew install p7zip                          # Extract function
    brew install pkg-config
    brew install ranger w3m                     # Ranger and previews
    brew install rclone                         # Automatic push and pull from drive
    brew install ripgrep
    brew install sox
    brew install stow                           # Stow dotfiles
    brew install swig
    brew install the_silver_searcher            # Grep on steroids
    brew install tmux                           # Terminal multiplexer
    brew install unrar                          # Extract function
    brew install wget                           # Download from command line
    brew install yarn                           # Package manager

    ### Terminal Font
    brew tap homebrew/cask-fonts
    # Open sauce has to be installed manually
    brew install font-fira-code-nerd-font
    brew install font-inconsolata-nerd-font
    brew install font-iosevka-nerd-font
    brew install font-meslo-lg-nerd-font

    ### GUI Applications
    # brew install shortcuts                      # spotlight shutdown now THIS WILL BREAK YOUR MAC
    # consider installing the logi options+ (first time installing it caused brightness buttons to not work? lol)
    # brew install qview                          # image viewer (better than builtin mac) free and open source
    brew install hammerspoon
    brew install mos                            # Separate inverse scroll for mouse and trackpad, DUH!
    brew install alfred                         # Better Spotlight
    brew install ballast                        # Auto-corrects volume balance, (weird macOS stuff)
    brew install calibre                        # Book manager
    brew install ccleaner                       # CleanUp
    brew install discord                        # Group calls
    brew install google-chrome                  # Web browser
    brew install karabiner-elements             # Swap Esc with Caps_lock
    brew install kitty                          # Best terminal
    brew install mactex                         # LaTex compiler
    brew install rectangle                      # Tiler
    brew install spotify                        # Music player
    brew install sublime-text                   # Fastest editor
    brew install telegram                       # Quickly transfer files
    brew install texstudio                      # Free and open source LaTex editor
    brew install the-unarchiver                 # Archiver "faster"
    brew install tomighty                       # Pomodoro timer
    brew install transmission                   # Torrent Downloader
    brew install visual-studio-code             # Text editor / IDE
    brew install vlc                            # Media Player
    brew install whatsapp                       # Messaging 
}

optional () {
    # https://www.elastic.co/guide/en/elasticsearch/reference/7.17/brew.html
    # brew install adobe-acrobat-reader           # Pdf reader
    brew install graphviz
    brew install intellij-idea                  # Paid, better java SQL IDE
    brew install intellij-idea-ce               # Free version
    brew install iterm2                         # Terminal emulator
    brew install jupyter                        # jupyter notebooks
    brew install keka                           # Archiver open source
    brew install meld                           # Diff software
    brew install obs                            # Screen recorder //very complicated on mac
    brew install qt5                            # Qt stuff
    brew install qtcreator                      # Qt IDE
    brew install r                              # Probabilitat i estadística
    brew install rstudio                        # Probabilitat i estadística IDE
    brew install slack                          # Work
    brew install tor-browser                    # Private and uncensored browsing
    brew install unetbootin                     # Burn iso's (or use dd command)
    brew install xquartz                        # PAR use GUI through SSH
    brew install skype                          # Videocalls
}

garbage() {
    brew tap elastic/tap
    brew install elastic/tap/elasticsearch-full

    pip3 install --user elasticsearch_dsl        # APA
    brew install --cask microsoft-edge
    brew install dbeaver-community adoptopenjdk       # BD
    brew install --cask eclipse-java                   # Java IDE
    brew install firefox # Gave it a try but google-chrome has automatic hyperlink support, print preview is better, faster icon bar loading
    brew install ghc                            # haskell compiler and ghci interpreter
    brew install glfw                           # OpenGL
    brew install swi-prolog
    brew install kdiff3                         # Git mergetool  
    # brew install --cask anaconda              # This should be installed from the official site so that it installs correctly
}

vim_install () {
    brew install macvim                         # Vim
    brew install neovim                         # NeoVim
    cd $HOME
    vim +PlugInstall +qall
    # Vim YouCompleteMe plugin install
    bash ~/.local/scripts/ycm.sh
    sudo npm install -g neovim
    python3 -m pip install --user --upgrade pynvim
    sudo gem install neovim
    sudo chown -R pol $XDG_DATA_HOME/
}

doom_emacs_install() {
    #chemacs
    git clone https://github.com/plexus/chemacs2.git ~/.emacs.d
    # required dependencies
    brew install git ripgrep
    # optional dependencies
    brew install coreutils fd
    # Installs clang
    xcode-select --install
    # brew tap railwaycat/emacsmacport
    # brew install emacs-mac --with-modules
    # ln -s /usr/local/opt/emacs-mac/Emacs.app /Applications/Emacs.app

    brew tap d12frosted/emacs-plus
    brew install emacs-plus --with-native-comp
    git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/doom-emacs
    ~/.config/doom-emacs/bin/doom install
    # ghcup installer for the general purpose language Haskell
    curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
    # Optional
    brew install gnuplot # doom org 
    brew install jq
    brew install black # python code formatting
    brew install pipenv # python 
    brew install shellcheck # shell script linting
    brew install hlint # flycheck for haskell
    brew install cabal # haskell-mode
    brew install aspell #  spell checker
    brew install editorconfig # elisp
    brew install glslang # elisp
    brew install cabal-install #haskell
    brew install dante
    brew install haskell-language-server
    echo "doom" | tee $HOME/.config/chemacs/profile
}

app_store_install() {
    brew install mas
    mas install 1274495053                      # Microsoft To Do
    mas install 1444383602                      # GoodNotes
    mas install 409183694                       # Keynote
    mas install 409201541                       # Pages
    mas install 409203825                       # Numbers
    mas install 441258766                       # Magnet
    mas install 497799835                       # Xcode
    #mas install 736189492                       # Notability
    #mas install 1147396723                      # WhatsApp
}

bloat_install() {
    brew install cowsay fortune coreutils       # Cows
    brew install cmatrix                        # Matrix
}

write_defaults() {
    # Disable automatic termination of inactive apps
    defaults write NSGlobalDomain NSDisableAutomaticTermination -bool true

    # Disable the “Are you sure you want to open this application?” dialog
    defaults write com.apple.LaunchServices LSQuarantine -bool false

    # Set sidebar icon size to medium
    defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 2

    # Show hidden files
    defaults write com.apple.finder AppleShowAllFiles true

    # Show everything on desktop
    defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
    defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
    defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
    defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

    # Do not create .DS_store on networks and USBs
    defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
    defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

    # Increase sound quality for Bluetooth headphones/headsets
    defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40

    # Disable auto-correct
    defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

    # Disable automatic period substitution as it’s annoying when typing code
    defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

    # Disable automatic capitalization as it’s annoying when typing code
    defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false

    # Disable press-and-hold for keys in favor of key repeat
    defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

    # Set a blazingly fast keyboard repeat rate
    defaults write NSGlobalDomain KeyRepeat -int 2 # How fast to reapeat, lower is faster
    defaults write NSGlobalDomain InitialKeyRepeat -int 25 # Time before repeating higher is slower

    # Set language and text formats
    # Note: if you’re in the US, replace `EUR` with `USD`, `Centimeters` with
    # `Inches`, `en_GB` with `en_US`, and `true` with `false`.
    defaults write NSGlobalDomain AppleLanguages -array "en-ES" "ca-ES" "es-ES"
    defaults write NSGlobalDomain AppleLocale -string "en_ES"
    # defaults write NSGlobalDomain AppleMeasurementUnits -string "Centimeters"
    # defaults write NSGlobalDomain AppleMetricUnits -bool true

    # Show language menu in the top right corner of the boot screen
    sudo defaults write /Library/Preferences/com.apple.loginwindow showInputMenu -bool true

    # bluetooth note wake up from sleep
    defaults -currentHost write com.apple.Bluetooth RemoteWakeEnabled 0

    # Set the timezone; see `sudo systemsetup -listtimezones` for other values
    sudo systemsetup -settimezone "Europe/Madrid" > /dev/null

    ###############################################################################
    # Chrome                                                                      # 
    ###############################################################################

    # Disable the all too sensitive backswipe on trackpads
    defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool false
    defaults write com.google.Chrome.canary AppleEnableSwipeNavigateWithScrolls -bool false

    # Disable the all too sensitive backswipe on Magic Mouse
    defaults write com.google.Chrome AppleEnableMouseSwipeNavigateWithScrolls -bool false
    defaults write com.google.Chrome.canary AppleEnableMouseSwipeNavigateWithScrolls -bool false
    
    ###############################################################################
    # Mac App Store                                                               #
    ###############################################################################

    # Enable the WebKit Developer Tools in the Mac App Store
    defaults write com.apple.appstore WebKitDeveloperExtras -bool true

    # Enable Debug Menu in the Mac App Store
    defaults write com.apple.appstore ShowDebugMenu -bool true

    # Enable the automatic update check
    defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true

    # Check for software updates daily, not just once per week
    defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

    # Download newly available updates in background
    defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1

    # Install System data files & security updates
    defaults write com.apple.SoftwareUpdate CriticalUpdateInstall -int 1

    # Automatically download apps purchased on other Macs
    defaults write com.apple.SoftwareUpdate ConfigDataInstall -int 1

    # Turn on app auto-update
    defaults write com.apple.commerce AutoUpdate -bool true

    # Allow the App Store to reboot machine on macOS updates
    defaults write com.apple.commerce AutoUpdateRestartRequired -bool true
}

optional_defaults() {
    # Disable smart dashes as they’re annoying when typing code
    # defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

    # Disable smart quotes as they’re annoying when typing code
    # defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
}

garbage_defaults() {
    # NEVER DO THIS, IT DISABLES KEYS ENTIRELY
    # Stop iTunes from responding to the keyboard media keys
    # launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist
    # launchctl load -w /System/Library/LaunchAgents/com.apple.rcd.plist
}

