#! /usr/bin/env bash
# Author: https://github.com/cuberhaus

### VARIABLES
scripts=$HOME/.local/scripts
source $scripts/bootstrap/arch_functions        # Include functions

### INSTALLATION
sudo pacman -Syu
echo "#! /bin/sh
export DISTRO=manjaro" > $HOME/.config/distro   # Distro variable
yay_install # Needed to install AUR packages

### ONLY CHANGE FROM HERE ON
base_install
i3_install

#applets                                        # Installs Cinnamon applets # implement pending
#bloat_install
#cinnamon_install
#games_install
#gnome_install
#optional
#plasma_install
#virtualbox_install

apps_AUR_install
cava_install
dwall
laptop_install
vim_install
wget -qO- https://git.io/papirus-folders-install | sh # Install folder colors https://github.com/PapirusDevelopmentTeam/papirus-folders
chsh -s $(which zsh)                            # Change default shell to zsh
