#! /usr/bin/env bash
# Author: https://github.com/cuberhaus

### VARIABLES
scripts=$HOME/.local/scripts
source $scripts/bootstrap/arch_functions        # Include functions
source $scripts/bootstrap/base_functions # Include functions

### INSTALLATION
sudo pacman -Syu
install_preparation
echo "#! /bin/sh
export DISTRO=manjaro" > $HOME/.config/distro   # Distro variable
sudo cp $HOME/dotfiles/dotfiles/.local/share/icons/Avatar.jpg /usr/share/icons/Avatar.jpg # Move avatar picture so that LightDM can find it
sudo cp $HOME/dotfiles/dotfiles/.local/share/icons/Avatar.jpg $HOME/.face # Move avatar picture so mugshot can find it

### ONLY CHANGE FROM HERE ON
base_install
i3_install
#xmonad_install

#applets                                        # Installs Cinnamon applets # implement pending
#bloat_install
#cinnamon_install
#games_install
#gnome_install
#optional
#plasma_install
#virtualbox_install
#dwall
#cava_install

#laptop_install
#vim_install
#wget -qO- https://git.io/papirus-folders-install | sh # Install folder colors https://github.com/PapirusDevelopmentTeam/papirus-folders
#chsh -s $(which zsh)                            # Change default shell to zsh

