#! /usr/bin/env bash
### VARIABLES
scripts=$HOME/.local/scripts

# Include functions
source $scripts/bootstrap/arch_install

### Installation starts here

echo "Is it the first time you run this script? [y/n]"
read FirstRun
cd ~/
sudo pacman -Syu
if [[ $FirstRun == y || $FirstRun == Y ]]; then
    echo "#! /bin/sh
    export DISTRO=manjaro" > ~/.config/distro
    yay_install # Needed to install AUR packages
fi

### Only change from here
cd ~/
base_install
i3_install
if [[ $FirstRun == y || $FirstRun == Y ]]; then
    ### FUNCTIONS
    #applets             # Installs Cinnamon applets # implement pending
    #bloat_install
    #cinnamon_install
    #games_install
    #gnome_install
    #optional
    #plasma_install
    #virtualbox_install
    apps_AUR_install
    cava_install
    dwall
    laptop_install
    vim_install

    wget -qO- https://git.io/papirus-folders-install | sh # Install folder colors https://github.com/PapirusDevelopmentTeam/papirus-folders
    chsh -s $(which zsh) # Change default shell to zsh
fi
