#! /usr/bin/env bash
# Author: https://github.com/cuberhaus

### First deploy dotfiles with stow, then execute scripts

### VARIABLES
scripts=$HOME/.local/scripts
source $scripts/bootstrap/ubuntu_functions      # Include functions
source $scripts/bootstrap/base_functions # Include functions

### INSTALLATION
sudo apt-get update; sudo apt-get full-upgrade  # Update
install_preparation
echo "#! /bin/sh
export DISTRO=ubuntu" > $HOME/.config/distro
brew_install

### ONLY CHANGE FROM HERE ON
base_install
vim_install

#albert_install
#bloat_install
#chrome_install
#emacs_install
#i3_install
#snap_install
#steam_install
#ubuntu_install
chsh -s $(which zsh)                            # Change default shell to zsh
