#! /usr/bin/env bash
# Author: https://github.com/cuberhaus

### VARIABLES
bootstrap_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_ROOT="$(cd "$bootstrap_dir/../../.." && pwd)"
export DOTFILES_ROOT
# Include functions
source "$bootstrap_dir/ubuntu_functions"
source "$bootstrap_dir/base_functions"
parse_bootstrap_args "$@"
configure_dual_boot_utc_rtc

### INSTALLATION
sudo apt-get update; sudo apt-get full-upgrade  # Update
bootstrap_stow_checkout ubuntu-windows
install_preparation
echo "#! /bin/sh
export DISTRO=ubuntu_windows" > "$HOME/.config/distro"

### ONLY CHANGE FROM HERE ON
base_install
sops_install
vim_install
windows_install

# emacs_install # This is not needed since emacs is installed natively through windows
#albert_install
#bloat_install
#chrome_install
#i3_install
#snap_install
#steam_install
#ubuntu_install

chsh -s "$(which zsh)"                          # Change default shell to zsh
