#! /usr/bin/env bash
### First deploy dotfiles with stow, then execute scripts

# Include functions
source ~/.local/bin/bootstrap/ubuntu_functions

### MAIN
echo "Is it the first time you run this script? [y/n]"
read FirstRun
if [[ $FirstRun == y ]]; then
    echo "#! /bin/sh
    export DISTRO=ubuntu" > ~/.config/distro
fi

base_install
brew_install
vim_install
chsh -s $(which zsh) # Change default shell to zsh
