#! /usr/bin/env bash
# Author: https://github.com/cuberhaus
flags="-y"
apt="sudo apt-get $flags install"
ycm="$HOME/.local/scripts/ycm.sh" # make sure it's there

base_install () { ## For windows install it's good to have this
    # System tools
    $apt autoconf 
    $apt automake 
    $apt bat                    # Better cat
    $apt build-essential 
    $apt cmake                  # To install ycm
    $apt curl 
    $apt exa                    # ls on steroids
    $apt file 
    $apt fonts-powerline 
    $apt fzf                    # Fuzzy finder
    $apt git 
    $apt gnome-shell 
    $apt htop                   # Show system resources
    $apt inkscape 
    $apt laptop-detect
    $apt libgtk-3-dev 
    $apt ncdu                   # Manage storage
    $apt neovim                 # Neovim
    $apt nodejs
    $apt npm 
    $apt optipng 
    $apt pkg-config 
    $apt python3 
    $apt python3-pip 
    $apt ranger w3m             # Ranger
    $apt rclone
    $apt ruby-dev
    $apt samba-common-bin 
    $apt sassc 
    $apt silversearcher-ag      # Better and faster ack (and grep)
    $apt stow
    $apt subversion             # To download repos
    $apt tmux                   # Terminal multiplexer
    $apt vim-gtk                # Vim with full functionality
    $apt yarn 
    $apt zsh
    $apt eog                    # To view images, can launch it from terminal (works on windows)
    $apt sshfs                  # To mount a remote file system with ssh (usefull to manipulate files with any ubuntu programs that you cannot install in remote) sshfs username@remote_host:/remote_directory ~/remote_dir
    chsh -s $(which zsh)
    git config --global credential.helper store
}

windows_install() {
    # wslc emacs (to create a shortcut to windows desktop to open emacs directly
    # https://wslutiliti.es/wslu/
    sudo add-apt-repository ppa:wslutilities/wslu
    sudo apt update
    sudo apt install wslu
    # wslc emacs # create shortcut from windows to ubuntu app
}

bloat_install () {
    brew install pipes-sh
    $apt cmatrix
    $apt cowsay                 # A cow displaying text
    $apt fortune                # Random quotes
    $apt neofetch 
}

ubuntu_install() {
    # GUI
    $apt LXAppearance           # Theme
    $apt arc-theme 
    $apt audacity
    $apt calibre
    $apt cpu-checker qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
    $apt gnome-screensaver      # Screensaver
    $apt gparted                # Manage partitions
    $apt pavucontrol            # Audio
    $apt thunderbird            # Email
    $apt timeshift              # Backups
    $apt transmission           # A simpler Torrent D.
    $apt vlc                    # Media player
    $apt dconf-editor           # advanced configs

    # Install Rstudio
    $apt r-base
    wget https://rstudio.org/download/latest/daily/desktop/jammy/rstudio-latest-amd64.deb
    sudo dpkg -i rstudio-latest-amd64.deb 

    # $apt kitty # cant even close it from gnome

    # One dark profile for gnome-terminal
    # https://github.com/denysdovhan/one-gnome-terminal
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/denysdovhan/gnome-terminal-one/master/one-dark.sh)"

    if [[ $FirstRun == y ]]; then
        sudo adduser `id -un` libvirt
        sudo adduser `id -un` kvm
    fi
}

albert_install () {
    if ! command -v albert 2>/dev/null; then
        cd $HOME
        curl https://build.opensuse.org/projects/home:manuelschneid3r/public_key | sudo apt-key add -
        echo 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/home:manuelschneid3r.list
        sudo wget -nv https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_20.04/Release.key -O "/etc/apt/trusted.gpg.d/home:manuelschneid3r.asc"
        sudo apt-get update
        sudo apt-get install albert
    fi
}

chrome_install () {
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    sudo apt install ./google-chrome-stable_current_amd64.deb
    rm google-chrome-stable_current_amd64.deb
}

emacs_install () {
    $apt emacs-gtk              # Emacs
    # Doom
    $apt git ripgrep            # required dependencies
    $apt tar fd-find clang      # optional dependencies
    $apt libtool                # vterm-module compilation

    # Chemacs installation to manage doom and personal
    [ -f ~/.emacs ] && mv ~/.emacs ~/.emacs.bak
    [ -d ~/.emacs.d ] && mv ~/.emacs.d ~/.emacs.default
    git clone https://github.com/plexus/chemacs2.git ~/.emacs.d

    echo "default" | tee $HOME/.config/chemacs/profile

    # systemctl --user enable emacs # this enables emacs as a daemon

    git clone https://github.com/hlissner/doom-emacs ~/.config/doom-emacs
    ~/.config/doom-emacs/bin/doom install
}

i3_install () {
    # Add repository and refresh apt
    sudo add-apt-repository ppa:kgilmer/speed-ricer
    sudo apt-get update
    $apt i3-gaps
    # Dependancies
    $apt alsa-utils
    $apt compton 
    $apt conky 
    $apt feh 
    $apt flameshot 
    $apt i3blocks 
    $apt kitty 
    $apt picom
    $apt player-ctl 
    $apt pulseaudio
    $apt pulseaudio 
    $apt pulseaudio-equalizer
    $apt python-dbus 
    $apt rofi 
    $apt udiskie
    $apt xbacklight
    $apt xdotool
    $apt xfce4-clipman
    $apt xss-lock
    $apt yad
    $apt zenity

    # Add current user to group video, type groups to see which groups you are in
    sudo usermod -a -G video $LOGNAME
    # Light setup | Enables brightness controls
    cd $HOME
    git clone https://github.com/haikarainen/light
    cd light
    ./autogen.sh
    ./configure && make
    sudo make install
    ./configure --with-udev && make
    sudo make install
}

snaps_install_optional() {
    sudo snap install android-studio --classic
    sudo snap install eclipse --classic
    sudo snap install flutter --classic
    sudo snap install jupyter
    sudo snap install postman
}

snaps_install() {
    sudo snap install code --classic
    sudo snap install discord
    sudo snap install intellij-idea-community --classic
    sudo snap install pycharm-community --classic
    sudo snap install skype --classic
    sudo snap install slack --classic
    sudo snap install spotify
    sudo snap install sublime-merge --classic
    sudo snap install sublime-text --classic
    sudo snap install walc
}

steam_install () {
    wget https://repo.steampowered.com/steam/archive/precise/steam_latest.deb
    sudo apt install ./steam_latest.deb
    rm steam_latest.deb
}

vim_install () {
    cd $HOME 
    vim +PlugInstall +qall                      # Update plugins
    bash $ycm                     # Vim YouCompleteMe plugin install
    sudo npm install -g neovim                  # npm on neovim
    python3 -m pip install --user --upgrade pynvim # Python for neovim
    sudo gem install neovim                     # Gem for neovim
    python3 $HOME/.vim/plugged/YouCompleteMe/install.py
}

optional() {
    $apt texlive-full doxygen   # Doxygen
    $apt virtualbox-qt          # Virtual machines
    # Qt G
    $apt build-essential libgl1-mesa-dev libglu1-mesa-dev
    $apt mesa-common-dev
    $apt qt-creator
    $apt qt5-default
    $apt qttools5-dev
    $apt qttools5-dev-tools
}

clone_repos() {
    git clone https://github.com/cuberhaus/WinDotfiles $HOME/repos/WinDotfiles
    git clone https://github.com/cuberhaus/dev $HOME/repos/dev
    git clone https://github.com/cuberhaus/TFG $HOME/repos/TFG
    git clone https://github.com/cuberhaus/docs $HOME/repos/docs
}

high_dpi_screen() {
    # To fix high dpi screens, two options, go to 200% scaling, or fractional scaling, fractional scaling causes blurry text, more power usage, lower speed.
    # We instead increase text scaling
    gsettings set org.gnome.desktop.interface text-scaling-factor 1.5
    # Increase cursor size Settings-> Accesibility -> Cursor size -> Medium
    gsettings set org.gnome.desktop.interface cursor-size 35
    # Set icons to Large 'small' to set it smaller
    gsettings set org.gnome.shell.extensions.ding icon-size 'large' 
}

touchpad_speed() {
    $apt xinput
    # xinput list (find device id)
    # xinput list-props [device id]
    # xinput set-prop [device id] [property id] [value]


}

