#! /usr/bin/env bash
# Author: https://github.com/cuberhaus
flags="-y"
apt="sudo apt-get $flags install"
ycm="$HOME/.local/scripts/ycm.sh" # make sure it's there
scripts="$HOME/.local/scripts"

base_install () { ## For windows install it's good to have this
    # System tools
    $apt autoconf 
    $apt automake 
    $apt bat                    # Better cat
    $apt build-essential 
    $apt cmake                  # To install ycm
    $apt curl 
    $apt eza                    # ls on steroids (exa replacement)
    $apt file 
    $apt fonts-powerline 
    $apt fzf                    # Fuzzy finder
    $apt git 
    $apt gnome-shell 
    $apt htop                   # Show system resources
    $apt inkscape 
    $apt laptop-detect
    $apt libgtk-3-dev 
    $apt ncdu                   # Manage storage
    $apt neovim                 # Neovim
    $apt nodejs
    $apt npm 
    $apt optipng 
    $apt pkg-config 
    $apt python3 
    $apt python3-pip 
    $apt ranger w3m             # Ranger
    $apt rclone
    $apt ruby-dev
    $apt samba-common-bin 
    $apt sassc 
    $apt silversearcher-ag      # Better and faster ack (and grep)
    $apt stow
    $apt subversion             # To download repos
    $apt tmux                   # Terminal multiplexer
    $apt vim-gtk                # Vim with full functionality
    $apt yarn 
    $apt zsh
    $apt eog                    # To view images, can launch it from terminal (works on windows)
    $apt sshfs                  # To mount a remote file system with ssh (usefull to manipulate files with any ubuntu programs that you cannot install in remote) sshfs username@remote_host:/remote_directory ~/remote_dir
    chsh -s "$(which zsh)"
    git config --global credential.helper store
}

windows_install() {
    # wslc emacs (to create a shortcut to windows desktop to open emacs directly
    # https://wslutiliti.es/wslu/
    sudo add-apt-repository ppa:wslutilities/wslu
    sudo apt update
    sudo apt install wslu
    # wslc emacs # create shortcut from windows to ubuntu app
}

bloat_install () {
    brew install pipes-sh
    $apt cmatrix
    $apt cowsay                 # A cow displaying text
    $apt fortune                # Random quotes
    $apt neofetch 
}

ubuntu_install() {
    # GUI
    $apt LXAppearance           # Theme
    $apt arc-theme 
    $apt audacity
    $apt calibre
    $apt cpu-checker qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
    $apt gnome-screensaver      # Screensaver
    $apt gparted                # Manage partitions
    $apt pavucontrol            # Audio
    $apt thunderbird            # Email
    $apt timeshift              # Backups
    $apt transmission           # A simpler Torrent D.
    $apt vlc                    # Media player
    $apt dconf-editor           # advanced configs

    # Install Rstudio
    $apt r-base
    if ! command -v rstudio &>/dev/null; then
        local rstudio_deb="/tmp/rstudio-latest-amd64.deb"
        wget -O "$rstudio_deb" https://rstudio.org/download/latest/daily/desktop/jammy/rstudio-latest-amd64.deb
        sudo dpkg -i "$rstudio_deb"
        rm -f "$rstudio_deb"
    else
        info "RStudio already installed, skipping."
    fi

    # $apt kitty # cant even close it from gnome

    # One dark profile for gnome-terminal
    # https://github.com/denysdovhan/one-gnome-terminal
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/denysdovhan/gnome-terminal-one/master/one-dark.sh)"

    if [[ $FirstRun == y ]]; then
        sudo adduser "$(id -un)" libvirt
        sudo adduser "$(id -un)" kvm
    fi
}

albert_install () {
    if ! command -v albert 2>/dev/null; then
        # Import the signing key into a dedicated keyring (apt-key is deprecated)
        curl -fsSL https://build.opensuse.org/projects/home:manuelschneid3r/public_key \
            | gpg --dearmor \
            | sudo tee /etc/apt/trusted.gpg.d/home-manuelschneid3r.gpg > /dev/null
        echo 'deb [signed-by=/etc/apt/trusted.gpg.d/home-manuelschneid3r.gpg] http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_20.04/ /' \
            | sudo tee /etc/apt/sources.list.d/home-manuelschneid3r.list
        sudo apt-get update
        sudo apt-get install -y albert
    fi
}

chrome_install () {
    if command -v google-chrome-stable &>/dev/null; then
        info "Google Chrome already installed, skipping."
        return
    fi
    local chrome_deb="/tmp/google-chrome-stable_current_amd64.deb"
    wget -O "$chrome_deb" https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    sudo apt install -y "$chrome_deb"
    rm -f "$chrome_deb"
}

emacs_install () {
    $apt emacs-gtk              # Emacs
    # Doom
    $apt git ripgrep            # required dependencies
    $apt tar fd-find clang      # optional dependencies
    $apt libtool                # vterm-module compilation

    # Chemacs installation to manage doom and personal
    if [ ! -d ~/.emacs.d ] || [ ! -f ~/.emacs.d/chemacs.el ]; then
        [ -f ~/.emacs ] && mv ~/.emacs ~/.emacs.bak
        [ -d ~/.emacs.d ] && mv ~/.emacs.d ~/.emacs.default
        git clone https://github.com/plexus/chemacs2.git ~/.emacs.d
    else
        info "Chemacs2 already installed, skipping."
    fi

    echo "default" | tee "$HOME/.config/chemacs/profile"

    # systemctl --user enable emacs # this enables emacs as a daemon

    if [ ! -d ~/.config/doom-emacs ]; then
        git clone https://github.com/hlissner/doom-emacs ~/.config/doom-emacs
        ~/.config/doom-emacs/bin/doom install
    else
        info "Doom Emacs already installed, skipping."
    fi
}

i3_install () {
    # Add repository and refresh apt
    sudo add-apt-repository -y ppa:kgilmer/speed-ricer
    sudo apt-get update
    $apt i3-gaps
    # Dependancies
    $apt alsa-utils
    $apt compton 
    $apt conky 
    $apt feh 
    $apt flameshot 
    $apt i3blocks 
    $apt kitty 
    $apt picom
    $apt player-ctl 
    $apt pulseaudio
    $apt pulseaudio 
    $apt pulseaudio-equalizer
    $apt python-dbus 
    $apt rofi 
    $apt udiskie
    $apt xbacklight
    $apt xdotool
    $apt xfce4-clipman
    $apt xss-lock
    $apt yad
    $apt zenity

    # Add current user to group video, type groups to see which groups you are in
    sudo usermod -a -G video "$LOGNAME"
    # Light setup | Enables brightness controls
    if ! command -v light &>/dev/null; then
        cd "$HOME" || exit
        git clone https://github.com/haikarainen/light
        cd "$HOME/light" || exit
        ./autogen.sh
        ./configure && make
        sudo make install
        ./configure --with-udev && make
        sudo make install
        cd "$HOME" || exit
        rm -rf "$HOME/light"
    else
        info "light already installed, skipping."
    fi
}

snaps_install_optional() {
    sudo snap install android-studio --classic
    sudo snap install eclipse --classic
    sudo snap install flutter --classic
    sudo snap install jupyter
    sudo snap install postman
    sudo snap install steam
}

snaps_install() {
    snap list code &>/dev/null                    || sudo snap install code --classic
    snap list discord &>/dev/null                 || sudo snap install discord
    snap list intellij-idea-professional &>/dev/null || sudo snap install intellij-idea-professional --classic
    #snap list intellij-idea-community &>/dev/null || sudo snap install intellij-idea-community --classic
    # snap list pycharm-community &>/dev/null     || sudo snap install pycharm-community --classic # Does not accept jupyter notebook
    snap list pycharm-professional &>/dev/null    || sudo snap install pycharm-professional --classic
    snap list skype &>/dev/null                   || sudo snap install skype --classic
    snap list slack &>/dev/null                   || sudo snap install slack --classic
    snap list spotify &>/dev/null                 || sudo snap install spotify
    snap list sublime-merge &>/dev/null           || sudo snap install sublime-merge --classic
    snap list sublime-text &>/dev/null            || sudo snap install sublime-text --classic
    snap list walc &>/dev/null                    || sudo snap install walc
}

# steam_install () {
#     wget https://repo.steampowered.com/steam/archive/precise/steam_latest.deb
#     sudo apt install ./steam_latest.deb
#     rm steam_latest.deb
# }

vim_install () {
    info "Installing vim/neovim plugins..."
    cd "$HOME" || exit
    vim +PlugInstall +qall                      # Update plugins
    bash "$ycm"                   # Vim YouCompleteMe plugin install
    sudo npm install -g neovim                  # npm on neovim
    python3 -m pip install --user --upgrade pynvim # Python for neovim
    sudo gem install neovim                     # Gem for neovim
    python3 "$HOME/.vim/plugged/YouCompleteMe/install.py"
}

optional() {
    $apt texlive-full doxygen   # Doxygen
    $apt virtualbox-qt          # Virtual machines
    # Qt G
    $apt build-essential libgl1-mesa-dev libglu1-mesa-dev
    $apt mesa-common-dev
    $apt qt-creator
    $apt qt5-default
    $apt qttools5-dev
    $apt qttools5-dev-tools
}

clone_repos() {
    info "Cloning repos..."
    mkdir -p "$HOME/repos"
    local failures=0
    local repos=(
        "cuberhaus/WinDotfiles"
        "cuberhaus/dev"
        "cuberhaus/TFG"
        "cuberhaus/docs"
    )
    for repo in "${repos[@]}"; do
        local name="${repo##*/}"
        if [ -d "$HOME/repos/$name" ]; then
            info "$name already exists, skipping"
        elif ! git clone "https://github.com/$repo" "$HOME/repos/$name"; then
            warn "Failed to clone $repo"
            ((failures++)) || true
        fi
    done
    if [ "$failures" -gt 0 ]; then
        warn "$failures repo(s) failed to clone"
    fi
}

# This has some problems with some apps that are seen very tiny, it is definitely not the perfect solution
high_dpi_screen() {
    # To fix high dpi screens, two options, go to 200% scaling, or fractional scaling, fractional scaling causes blurry text, more power usage, lower speed.

    # We instead increase text scaling
    gsettings set org.gnome.desktop.interface text-scaling-factor 1.3

    # Increase cursor size Settings-> Accesibility -> Cursor size -> Medium
    gsettings set org.gnome.desktop.interface cursor-size 35
    # Set icons to Large 'small' to set it smaller
    gsettings set org.gnome.shell.extensions.ding icon-size 'large' 
}

anaconda () {
    # Pre-requisites
    apt-get install libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6
    
    # Install anaconda
    curl -O https://repo.anaconda.com/archive/Anaconda3-2023.09-0-Linux-x86_64.sh
}

# This has no solution in wayland yet, unfortunately
touchpad_speed() {
    $apt xinput
    # xinput list (find device id)
    # xinput list-props [device id]
    # xinput set-prop [device id] [property id] [value]
}

