#! /usr/bin/env bash
# Author: https://github.com/cuberhaus

### VARIABLES
scripts=$HOME/.local/scripts
source $scripts/bootstrap/ubuntu_functions  # Include functions

### INSTALLATION
sudo apt-get update; sudo apt-get full-upgrade
echo "#! /bin/sh
export DISTRO=ubuntu" > $HOME/.config/distro

### ONLY CHANGE FROM HERE ON
brew_install
base_install

#albert_install
#bloat_install
#emacs_install
#steam_install

chrome_install
i3_install
snap_install
ubuntu_install
vim_install
chsh -s $(which zsh)                        # Change default shell to zsh
