#!/usr/bin/env bash
# Arch bootstrap UNINSTALL
# Author: https://github.com/cuberhaus
set -euo pipefail

### VARIABLES
scripts="$HOME/.local/scripts"
source "$scripts/bootstrap/base_functions"
source "$scripts/bootstrap/uninstall_arch_functions"

### UNINSTALLATION
info "Preparing to uninstall Arch bootstrap dependencies..."

read -r -p "This will remove base packages, drivers, i3, xmonad, vim plugins, and more. Are you sure? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    vim_uninstall
    i3_uninstall
    xmonad_uninstall
    arch_uninstall
    laptop_uninstall
    dwall_uninstall
    papirus_uninstall
    base_uninstall

    if [ "$(basename "$SHELL")" == "zsh" ]; then
        info "Currently using zsh. To revert to bash, run: chsh -s \$(which bash)"
    fi

    info "Uninstallation complete. A system reboot is recommended."
else
    info "Uninstallation aborted."
fi
