# autogenerated by txs
#include:amsgen
\GenericError#S
\GenericInfo#S
\GenericWarning#S
\addtocounter{arg1}{arg2}#S
\csname#S
\mathhexbox{arg1}{arg2}{arg3}#S
\stepcounter{arg1}#S
\text#S
\__hook amsgen#S
\unprocessedoptions-amsgen.sty#S
amsgen.sty#S
csnameendcsname#S
