[global]
    hostname = pol-server

[db]
    mode = dbengine
    storage tiers = 1
    dbengine tier 0 disk space MB = 2048
    dbengine tier 0 retention days = 90

[web]
    bind to = 127.0.0.1 192.168.1.34
    default port = 19999
    allow connections from = localhost 192.168.1.*
    allow dashboard from = localhost 192.168.1.*
    allow mcp from = localhost
    allow badges from = localhost
    allow streaming from = localhost
    allow netdata.conf from = localhost
    allow management from = localhost