#! /usr/bin/env bash
# YOU NEED TO ADD YOURSELF TO WHEEL AND TO VIDEO
# video makes backlight work and wheel gives you sudo privilege
# usermod -a -G wheel video input
arch_install () {
    sudo pacman -S xorg
    # Drivers
    # Add force composition pipeline in nvidia-settings
    sudo pacman -S nvidia nvidia-settings xf86-video-intel
    # Theme
    sudo pacman -S lxappearance gtk2 gtk3 arc-gtk-theme cmatrix arc-icon-theme
    # Notifications
    sudo pacman -S dunst
    # Bluetooth
    sudo pacman -S bluez bluez-utils
    # Preview images on ranger
    sudo pacman -S w3m
    # Image viewer
    sudo pacman -S nomacs
    # Pdf viewer
    sudo pacman -S zathura zathura-pdf-mupdf zathura-cb
    # Office
    sudo pacman -S libreoffice-still
    # Audio | Equalizer qpaeq
    sudo pacman -S pulseaudio pulseaudio-equalizer pulseaudio-bluetooth
    # Video player
	sudo pacman -S vlc
    mkdir ~/.cache/vlc
    # Apps
    sudo pacman -S thunderbird chromium thunar albert

    # Terminal
    sudo pacman -S rxvt-unicode gvim exa ranger bash-completion
    # Fuzzy finder
    sudo pacman -S fzf
    # Tmux
    sudo pacman -S tmux
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    # Manage storage
    sudo pacman -S ncdu
    # System tools
    sudo pacman -S base-devel dhcpcd git python3 stow
    # AUR
    sudo pacman -S --needed base-devel
    # Ntp for time syncro
    #https://wiki.archlinux.org/index.php/Systemd-timesyncd
    systemctl enable systemd-timesyncd.service
    systemctl disable ntpd.service
	#systemctl stop ntpd.service
	#systemctl start systemd-timesyncd.service
	#systemctl enable systemd-timesyncd.service 

    # Display manager
    #systemctl enable lightdm.service
    sudo pacman -S lightdm-gtk-greeter lightdm
    # Fonts
    sudo pacman -S ttf-font-awesome ttf-dejavu ttf-liberation ttf-droid ttf-ubuntu-font-family ttf-roboto noto-fonts
    # Doxygen
    sudo pacman -S doxygen texlive-most graphviz gcc

}

vim_install () {
    cd ~/
    vim +PlugInstall +qall
    # Vim YouCompleteMe plugin install
    bash ~/scripts/ycm.sh
}

i3_install () {

    sudo pacman -S i3-gaps compton rofi i3blocks python-dbus
    # Wallpaper
    sudo pacman -S feh
    # Brightness
    sudo pacman -S light
    # battery plus
    sudo pacman -S awk bc upower
    sudo pacman -S acpi
    # calendar
    sudo pacman -S yad xdotool
    # Audio
    sudo pacman -S pulseaudio alsa-utils
}

snap_install () {
    # https://wiki.archlinux.org/index.php/Snap

	git clone https://aur.archlinux.org/snapd.git
	cd snapd
	makepkg -si
	sudo systemctl enable --now apparmor.service
	sudo systemctl enable --now snapd.apparmor.service
	sudo systemctl enagle --now snapd.socket
}

spotify_install () {
    # https://wiki.archlinux.org/index.php/Spotify
    git clone https://aur.archlinux.org/spotify.git
    cd spotify
    curl -sS https://download.spotify.com/debian/pubkey.gpg | gpg --import -
    makepkg -si
}

Network_manager_install () {
    # Network Manager and enable daemon on startup
    sudo pacman -S networkmanager
    #systemctl enable NetworkManager.service
    # Gui
    sudo pacman -S nm-connection-editor
    # Applet
    sudo pacman -S nm-applet
}

Auto-mounting () {
# https://wiki.archlinux.org/index.php/USB_storage_devices
    # Daemon to manipulate storage devices
    sudo pacman -S udisks2
    # Automater
    sudo pacman -S udiskie
}

base16 () {
    git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell
}

yay_install () {
    # Microsoft fonts
    yay -S ttf-ms-fonts
    # Backups
    yay -S timeshift
    yay -S skypeforlinux-stable-bin
    yay -S android-sdk
    yay -S slack-desktop
    # Lockscreen
    yay -S betterlockscreen
}

cava_install () {
    pacman -S base-devel fftw ncurses alsa-lib iniparser pulseaudio
    git clone https://github.com/karlstav/cava
    cd cava
    ./autogen.sh
    ./configure
    make
    make install
    #make uninstall
}

# do this but i dont know exactly how
do_once () {
    sudo echo "Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
		Option "NaturalScrolling" "true"
EndSection"  >> /etc/X11/xorg.conf.d/30-touchpad.conf
}

games_install () {
    sudo pacman -S steam lutris
}

### Installation starts here

cd ~/
# Update
sudo pacman -Syu
# Base install
#Network_manager_install
arch_install
i3_install
vim_install
spotify_install
Auto-mounting
base16
sudo pacman -S discord
# configure nvidia
nvidia-xconfig
