#!/bin/sh
# Author: https://github.com/cuberhaus

ex ()
{
    if [ -f "$1" ] ; then
        case "$1" in
            *.tar.bz2)   tar xjf "$1"   ;;
            *.tar.gz)    tar xzf "$1"   ;;
            *.bz2)       bunzip2 "$1"   ;;
            *.rar)       unrar x "$1"   ;;
            *.gz)        gunzip "$1"    ;;
            *.tar)       tar xf "$1"    ;;
            *.tbz2)      tar xjf "$1"   ;;
            *.tgz)       tar xzf "$1"   ;;
            *.zip)       unzip "$1"     ;;
            *.Z)         uncompress "$1";;
            *.7z)        7z x "$1"      ;;
            *.deb)       ar x "$1"      ;;
            *.tar.xz)    tar xf "$1"    ;;
            *.tar.zst)   unzstd "$1"    ;;
            *)           echo "'$1' cannot be extracted via ex()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}
echo "Do you want to install cinnamon applets? [y/n]"
read -r install
if [[ "$install" == y ]]; then
    dest="$HOME/.local/share/cinnamon/applets"
    mkdir -p "$dest"
    cd "$dest" || exit

    urls=(
        "https://cinnamon-spices.linuxmint.com/files/applets/SpicesUpdate@claudiux.zip"
        "https://cinnamon-spices.linuxmint.com/files/applets/clean-show-desktop@filipetorresbr.zip"
        "https://cinnamon-spices.linuxmint.com/files/applets/weather@mockturtl.zip"
        "https://cinnamon-spices.linuxmint.com/files/applets/color-picker@fmete.zip"
        "https://cinnamon-spices.linuxmint.com/files/applets/show-hide-applets@mohammad-sn.zip"
        "https://cinnamon-spices.linuxmint.com/files/applets/force-quit@cinnamon.org.zip"
        "https://cinnamon-spices.linuxmint.com/files/applets/betterlock.zip"
        "https://cinnamon-spices.linuxmint.com/files/applets/Cinnamenu@json.zip"
        "https://cinnamon-spices.linuxmint.com/files/desklets/calendar@deeppradhan.zip"
        "https://cinnamon-spices.linuxmint.com/files/desklets/diskspace@schorschii.zip"
    )

    echo "Downloading applets in parallel..."
    pids=()
    files=()
    for url in "${urls[@]}"; do
        file="${url##*/}"
        wget -q "$url" -O "$file" &
        pids+=($!)
        files+=("$file")
    done

    failures=0
    for i in "${!pids[@]}"; do
        if wait "${pids[$i]}"; then
            ex "${files[$i]}"
        else
            echo "Failed to download ${files[$i]}"
            ((failures++)) || true
        fi
    done
    if [ "$failures" -gt 0 ]; then
        echo "$failures download(s) failed"
    fi
fi
