#!/bin/bash
 
spotify_pid=`pgrep spotify | head -1`
 
if [[ ! -z $spotify_pid ]]; then
   found=false
   while [ "$found" = false ] && IFS= read -r line; do
      pid=`echo $line | awk '{ print $3 }'`
      if [ "$pid" = "$spotify_pid" ]; then
         title=`echo $line | awk '{$1=$2=$3=$4=""; print $0 }' | tr -s ' '`
         echo "Spotify: ${title}"
         found=true
      fi
   done < <(wmctrl -lp)
fi
