#!/usr/bin/env python3
"""Audit cuberhaus workspace repos against declared policies.

Reads:
  cuberhaus-workspace/repos.json     # Built by build-repos.py
  cuberhaus-workspace/policies.json  # Declarative contract

For each repo in repos.json with state in audited_states, fetches live
GitHub repo settings via `gh api repos/cuberhaus/<name>` and compares
against policies.json. Reports drift as a Markdown table on stdout.

Read-only: never PATCHes settings, never opens PRs, never edits anything.

Exit codes:
  0 = no drift (all audited repos pass all checks)
  1 = drift detected

Usage:
  python3 audit-policies.py                                      # default paths
  python3 audit-policies.py repos.json policies.json             # custom paths
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path


def gh_api(path: str) -> dict | None:
    """Return parsed JSON from `gh api <path>`, or None on failure."""
    try:
        result = subprocess.run(
            ["gh", "api", path],
            check=True, capture_output=True, text=True,
        )
        return json.loads(result.stdout)
    except (subprocess.CalledProcessError, json.JSONDecodeError) as e:
        print(f"[audit] WARN: gh api {path} failed: {e}", file=sys.stderr)
        return None


def dotted_get(data: dict, key: str):
    """Walk `data` by dotted-path key. Returns None if any segment is missing.

    Example: dotted_get(repo, 'security_and_analysis.secret_scanning.status')
    """
    current = data
    for part in key.split("."):
        if not isinstance(current, dict) or part not in current:
            return None
        current = current[part]
    return current


def audit_repo(repo: dict, policies: dict) -> list[str]:
    """Return list of human-readable drift messages for one repo."""
    name = repo["name"]
    drift: list[str] = []

    # File-presence checks (from repos.json)
    for key, expected in policies.get("files", {}).items():
        actual = repo.get(key, False)
        # `has_skills` is "root"/"web"/false; coerce truthy. Same for "has_skills" if added.
        actual_truthy = bool(actual) if not isinstance(actual, str) else True
        if actual_truthy != expected:
            drift.append(f"`{key}`: expected `{expected}`, got `{actual}`")

    # Conditional: repos with skills installed should have the monthly
    # skills-update workflow. Catches "installed skills but forgot the
    # automation". Not a flat policy because it only applies when has_skills.
    if repo.get("has_skills") and not repo.get("has_skills_workflow"):
        drift.append(
            "`has_skills_workflow`: required because `has_skills` is truthy, "
            "but `.github/workflows/skills-update.yml` is missing"
        )

    # GitHub settings checks (fetch live). Keys may use dotted paths to walk
    # nested fields like 'security_and_analysis.secret_scanning.status'.
    setting_policies = policies.get("settings", {})
    non_empty_policies = policies.get("non_empty", [])
    if setting_policies or non_empty_policies:
        live = gh_api(f"repos/cuberhaus/{name}")
        if live is None:
            drift.append("(could not fetch live settings)")
        else:
            for key, expected in setting_policies.items():
                actual = dotted_get(live, key) if "." in key else live.get(key)
                if actual != expected:
                    drift.append(f"`{key}`: expected `{expected}`, got `{actual}`")
            for key in non_empty_policies:
                actual = dotted_get(live, key) if "." in key else live.get(key)
                if not actual:
                    drift.append(f"`{key}`: expected non-empty value, got `{actual}`")

    return drift


def render_report(audited: list[tuple[str, list[str]]]) -> str:
    """Render the drift table as Markdown."""
    lines: list[str] = []
    lines.append("# Workspace policies audit")
    lines.append("")

    drifting = [(name, drift) for name, drift in audited if drift]
    clean = [name for name, drift in audited if not drift]

    if not drifting:
        lines.append(f"All {len(audited)} audited repos pass all policy checks.")
        lines.append("")
        lines.append("Audited: " + ", ".join(f"`{n}`" for n in sorted(clean)))
        return "\n".join(lines) + "\n"

    lines.append(
        f"{len(drifting)} of {len(audited)} audited repos have policy drift "
        f"({len(clean)} clean)."
    )
    lines.append("")
    lines.append("| Repo | Drift |")
    lines.append("|------|-------|")
    for name, drift in sorted(drifting):
        bullets = "<br>".join(f"- {d}" for d in drift)
        lines.append(f"| `{name}` | {bullets} |")
    lines.append("")
    if clean:
        lines.append("## Clean")
        lines.append("")
        lines.append(", ".join(f"`{n}`" for n in sorted(clean)))
        lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(
        "*Generated by [`audit-policies.py`](cuberhaus-workspace/scripts/audit-policies.py) "
        "from [`policies.json`](cuberhaus-workspace/policies.json) and "
        "[`repos.json`](cuberhaus-workspace/repos.json).*"
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    repos_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("cuberhaus-workspace/repos.json")
    policies_path = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("cuberhaus-workspace/policies.json")

    if not repos_path.is_file():
        print(f"[audit] FATAL: repos file not found: {repos_path}", file=sys.stderr)
        return 2
    if not policies_path.is_file():
        print(f"[audit] FATAL: policies file not found: {policies_path}", file=sys.stderr)
        return 2

    repos = json.loads(repos_path.read_text(encoding="utf-8"))
    policies = json.loads(policies_path.read_text(encoding="utf-8"))

    audited_states = set(policies.get("audited_states", []))
    if not audited_states:
        print("[audit] FATAL: policies.audited_states is empty", file=sys.stderr)
        return 2

    selected = [r for r in repos if r.get("state") in audited_states and r.get("cloned")]
    print(
        f"[audit] Auditing {len(selected)} of {len(repos)} repos "
        f"(states: {', '.join(sorted(audited_states))})",
        file=sys.stderr,
    )

    results: list[tuple[str, list[str]]] = []
    for repo in selected:
        drift = audit_repo(repo, policies)
        results.append((repo["name"], drift))

    print(render_report(results))

    drifting = sum(1 for _, drift in results if drift)
    print(f"[audit] Done: {drifting} repos with drift, {len(results) - drifting} clean", file=sys.stderr)
    return 1 if drifting else 0


if __name__ == "__main__":
    sys.exit(main())
