#!/bin/sh

BASE16_SHELL=$HOME/.config/base16-shell/
[ -s $BASE16_SHELL/profile_helper.sh ] && \
    eval "$($BASE16_SHELL/profile_helper.sh)"

dconf load /org/cinnamon/ < ~/.config/cinnamon/dark/cinnamon.dconf
dconf load /org/nemo/ < ~/.config/cinnamon/dark/nemo.dconf
dconf load /org/gtk/ < ~/.config/cinnamon/dark/gtk.dconf
dconf load /org/gnome/ < ~/.config/cinnamon/dark/gnome.dconf

# Change folder colors
papirus-folders -C blue --theme Papirus-Dark
# Change terminal color
base16_onedark
