#!/bin/sh
BASE16_SHELL=$HOME/.config/base16-shell/
[ -s $BASE16_SHELL/profile_helper.sh ] && \
              eval "$($BASE16_SHELL/profile_helper.sh)"

dconf load /org/cinnamon/ < ~/.config/cinnamon/light/cinnamon.dconf
dconf load /org/nemo/ < ~/.config/cinnamon/light/nemo.dconf
dconf load /org/gtk/ < ~/.config/cinnamon/light/gtk.dconf
dconf load /org/gnome/ < ~/.config/cinnamon/light/gnome.dconf

# Change folder colors to teal
papirus-folders -C green --theme Papirus-Dark
# Change termian color to a light one, similar to 
base16_classic-light
#base16_mexico-light
